ALTER TABLE `ReportComments` ADD `challenges` MEDIUMTEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL AFTER `comments`, ADD `approachtopathway1` MEDIUMTEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL AFTER `challenges`, ADD `approachtopathway2` MEDIUMTEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL AFTER `approachtopathway1`, ADD `finalnotes` MEDIUMTEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL AFTER `approachtopathway2`, ADD `supplementaryinformation` MEDIUMTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL AFTER `finalnotes`;



ALTER TABLE  `ReportComments` CHANGE  `Challenges`  `challenges` MEDIUMTEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL ,
CHANGE  `Approachtopathway1`  `approachtopathway1` MEDIUMTEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL ,
CHANGE  `Approachtopathway2`  `approachtopathway2` MEDIUMTEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL ,
CHANGE  `Finalnotes`  `finalnotes` MEDIUMTEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL ,
CHANGE  `SUPPLEMENTARYINFORMATION`  `supplementaryinformation` MEDIUMTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL ;

INSERT INTO `MessageTemplate` (`id`, `name`, `roleTypeId`, `notificationType`, `messageType`, `messageSubject`, `templateString`, `templateParams`, `isActive`) VALUES
(24, 'TRIAL_STUDENTFINALREPORT', 2, 'EMAIL', 'TRIAL_STUDENT_FINAL_REPORT', 'Your Final Lodestar Report.', 'Dear ${UserName}, <br><p>Congratulations! You have completed the Lodestar''s unique Career Guidance Program.  You may log into your Lodestar account to view and download the final report in the Summary section.</p><br><br><p>This report captures a summary of all the discussions and details of the decisions made during the program.  If you have any queries, you can contact your Guidance Specialist or write us at <a href="mailto:guidance@lodestar.guru">guidance@lodestar.guru</a> or call us at +91 8026714555 or +91 8971520007.</p><br><br><br>- Team Lodestar', 'UserName', 1),
(25, 'TRIAL_STUDENTFINALREPORT_PARENT', 2, 'EMAIL', 'TRIAL_STUDENT_FINAL_REPORT_PARENT', 'Lodestar Final Report of your child.', 'Dear Parent, <br><br><p>Congratulations! Your child has completed Lodestar’s unique Career Guidance Program.  You may log into your Lodestar account to view and download the final report in the Summary section.</p><br><br><p>This report captures a summary of all the discussions and details of the decisions made during the program.  If you have any queries, you can contact your Guidance Specialist or write us at <a href="mailto:guidance@lodestar.guru">guidance@lodestar.guru</a> or call us at +91 8026714555 or +91 8971520007.</p><br><br><br>- Team Lodestar', 'UserName', 1);